image: maven:3.6-jdk-8-slim

stages:
  - build
  - unit-test
  - integration-test
  - package

compile:
  stage: build
  script:
    - mvn compile

unit-test:
  stage: unit-test
  script: 
    - mvn test

integration-test:
  stage: integration-test
  script:
    - mvn integration-test

package:
  stage: package
  script:
    - mvn package




